export const initialWorldRatings = {
  "desk-straight": [6, "Flat inset slab; drawer and wood character disappear at gameplay size."],
  "desk-corner": [6, "Disjoint slab outline and bare surface; join reads as two generic tables."],
  "chair-office": [5.5, "Wooden dining-chair silhouette; weak cushion separation and pale edges."],
  "sofa-straight": [6, "Rigid pads, wide exposed frame gaps and weak white upholstery definition."],
  "sofa-corner": [6, "Rigid segmented cushions and visually unfinished inside corner."],
  "table-meeting": [6.5, "Large flat top with sparse mechanical joints and little material depth."],
  "table-workbench": [6.5, "Readable trestle but oversized flat top lacks finish and joinery."],
  "table-cafe": [6.5, "Featureless disk; pedestal and rim barely distinguish materials."],
  "plant-floor": [7, "Thin overlapping leaves and oversized uniform green pot opening."],
  "plant-planter-row": [5.5, "Identical flowers in rigid rows; sparse foliage and plain container."],
  "outdoor-garden-bed": [5, "Mechanical flower grid dominates a large empty dark soil rectangle."],
  "outdoor-pool": [6, "Uniform sparkle grid, flat border and weak water depth."],
  "decor-desk-plant": [7, "Leaf overlap forms a tangled silhouette at small size."],
  "decor-laptop": [7, "Very thin screen and sparse keyboard lose definition in side views."],
  "decor-lamp": [5, "Shade and base merge into an egg silhouette; stem is unclear."],
  "equipment-whiteboard": [7, "Pale frame loses definition and thin supports appear fragile."],
  "equipment-checklist": [7, "Checklist is legible but pale frame and supports lack depth."],
  "equipment-arcade": [6, "Disconnected stepped housing and exposed side cavities; weak marquee."],
  "equipment-gong": [7, "Plain rectangular stand; gong center reads flat and lacks suspension detail."],
  "equipment-falling-blocks": [7.5, "Clear game screen, but generic slab and washed-out white frame."],
  "equipment-tic-tac-toe": [7.5, "Clear board; table frame is flat and white legs disappear."],
  "equipment-chess": [7.5, "Board is recognizable; tiny pieces and pale frame lose depth."],
  "desk-standing": [6, "Generic long-legged table; no convincing adjustable desk detail."],
  "chair-lounge": [6, "Split flat seat resembles a narrow loveseat; cushion shaping is weak."],
  "table-round": [6.5, "Large blank disk with little rim, material or pedestal definition."],
  "plant-palm": [6.5, "Sparse fronds alias into fine noise above an oversized pot opening."],
  "outdoor-bench": [7, "Readable slats, but rigid edges and weak white material definition."],
  "decor-monitor": [7, "Very thin screen and oversized blank base; side view is hard to read."],
  "decor-coffee": [8, "Cup, handle, coffee and saucer remain recognizable at the small footprint."],
  "equipment-bookshelf": [6.5, "Unfinished flat top and sides dominate otherwise readable books."],
  "floor-tile": [4, "Repeated fields expose transparent seams and direction-dependent missing joints; grass is speckled."],
  "infrastructure-portal": [6, "Flat concentric disk; small runes disappear and the center lacks character."],
  "desk-compact": [6, "Blank top and generic legs; writing-desk details disappear."],
  "desk-executive": [6.5, "Fluted front reads well, but the broad top remains an unshaped slab."],
  "desk-drafting": [7, "Plan and ruler are recognizable; paper and desk are flat and sparse."],
  "desk-gaming": [6, "Large plain dark mat and generic wood legs do not convey gaming equipment."],
  "desk-reception": [6.5, "Useful raised ledge, but broad flat surfaces and abrupt joins lack finish."],
  "desk-atelier": [6, "Supply cubbies look like upright solid bars; desk lacks crafted detail."],
  "chair-stool": [6.5, "Plain square cushion and wooden frame; pale piping disappears."],
  "chair-dining": [6.5, "Generic squared back and seat; white version loses its silhouette."],
  "chair-beanbag": [6, "Two overlapping balls read as separate objects rather than a soft bag."],
  "sofa-loveseat": [6, "Rigid seat pads and blank back; gaps expose the wooden frame."],
  "sofa-velvet": [6.5, "Tiny gold dots do not convey tufting; rigid seat pads dominate."],
  "table-coffee": [6.5, "Basic flat rectangle with sparse joints and little edge definition."],
  "table-side": [6.5, "Plain tiny slab with weak white edge contrast."],
  "table-picnic": [6.5, "Readable trestles but large flat tabletop lacks wood character."],
  "table-marble": [7, "Veins are thin and fragmented; top and rim lack convincing stone depth."],
  "plant-cactus": [7.5, "Recognizable arms and bloom; uniform pot and weak cactus ribs limit finish."],
  "plant-bonsai": [5.5, "Stacked foliage blobs conceal the trunk and do not form a bonsai silhouette."],
  "plant-monstera": [6.5, "Overlapping lobes produce tangled outlines rather than clear split leaves."],
  "decor-terrarium": [6, "Frame and foliage merge into a small circular knot; glass form is unclear."],
  "outdoor-fountain": [7, "Readable tiered water, but heavy concentric ripples and flat stone colors."],
  "outdoor-lantern": [5.5, "Roof is a flat square and the body loses its lantern silhouette."],
  "outdoor-topiary": [5.5, "Stacked balls do not read as a continuous spiral."],
  "decor-pr-tray": [8, "Tray lip, stacked paperwork and colored tab read clearly in all directions."],
  "decor-books": [7.5, "Readable stack but nearly identical pink covers obscure design differences."],
  "decor-vase": [6.5, "Solid egg shape with no clear opening or glaze definition."],
  "decor-clock": [7, "Face is recognizable but side and back are plain blocks."],
  "decor-headphones": [7, "Band is thin and cups merge with the stand at small scale."],
  "decor-trophy": [7, "Small flat crystal and large blank base need stronger facet definition."],
  "storage-filing": [6.5, "Drawer fronts read, but the top and sides look like unfinished blocks."],
  "storage-locker": [6.5, "Doors and vents read; broad top, sides and rear lack panel detail."],
  "storage-credenza": [6.5, "Generic slab cabinet with thin handles and little joinery."],
  "storage-cubby": [6.5, "Books are tiny under a dominating blank top; cubbies lack depth."],
  "storage-display": [6.5, "Ornaments resemble dots in open shelves; display framing is weak."],
  "light-floor": [6, "Shade and oversized circular foot dominate; fabric and stem lack definition."],
  "light-arc": [7, "Readable arch, but small pale shade and large flat base look unfinished."],
  "light-paper": [7, "Recognizable ribs, but harsh fine lines and flat base reduce cohesion."],
  "light-crystal": [6.5, "Thin pale shards alias into noise above a large flat base."],
  "breakroom-fridge": [6, "Boxy body and top do not convey a retro appliance; pale handles vanish."],
  "breakroom-coffee-bar": [7, "Machine and cups read, but plain counter and cabinet lack finish."],
  "breakroom-water-cooler": [7, "Bottle and taps read; body and bottle remain flat blocks."],
  "chair-ottoman": [6.5, "Plain circular pad with weak upholstery and nearly invisible white outline."],
  "rug-woven": [6, "Flat motifs, borders cross at corners, and repeated fields look mechanical."],
  "rug-round": [5.5, "Plain polygonal disk with an irregular border and no visible weave."],
  "decor-shoji-screen": [8.5, "Clear framed paper panels, fitted feet and restrained floral details in every view."],
  "breakroom-tea-cart": [8.5, "Coherent lacquer, tea service, wheels and open shelves; all designs read clearly."],
  "plant-sakura": [8, "Airy blossom silhouette, visible branch structure and coordinated glazed pot."],
  "decor-maneki-cat": [8, "Cute ears, raised paw and coin remain readable at the small footprint."],
  "outdoor-koi-pond": [6.5, "Koi and lilies read, but sparkle grid and flat rectangular coping dominate."],
  "rug-tatami": [5.5, "High-contrast stripes look synthetic; repeated fields amplify aliasing and striping."],
  "sofa-reading-bench": [7, "Coherent spindle back, but flat pads and plain surfaces need softness."],
  "table-chabudai": [6.5, "Low scale reads correctly, but the top is an empty flat rectangle."],
  "plant-bamboo": [7, "Jointed stalks read, but tiny leaves create a brittle, noisy canopy."],
  "light-stone-lantern": [7, "Recognizable stone roof and window, but roof and plinth lack sculpted depth."],
  "decor-wind-chimes": [7.5, "Hanging parts read, but stand and base are flat and small chimes lose contrast."],
  "decor-pinwheel": [7.5, "Cute silhouette, but thin blades and stem need clearer material separation."],
};
