import type {
  Area,
  BootstrapData,
  ChatMessage,
  Conversation,
  Floor,
  FloorLayout,
  GameScore,
  Invitation,
  Meeting,
  Member,
  MiniGameDefinition,
  Office,
  Team,
  WorldObject,
} from "@workhard/shared";

const team: Team = {
  id: "team-northstar",
  name: "Northstar",
  slug: "northstar",
  accent: "#6c5ce7",
};

const office: Office = {
  id: "office-northstar-hq",
  teamId: team.id,
  name: "Northstar HQ",
};

const floors: Floor[] = [
  {
    id: "floor-studio",
    officeId: office.id,
    name: "Studio",
    level: 1,
    width: 1600,
    height: 1000,
    spawn: { x: 770, y: 890 },
    background: "#e7e0d3",
  },
  {
    id: "floor-rooftop",
    officeId: office.id,
    name: "Rooftop",
    level: 2,
    width: 1280,
    height: 820,
    spawn: { x: 640, y: 710 },
    background: "#dce7dd",
  },
];

const members: Member[] = [
  {
    id: "user-maya",
    name: "Maya Chen",
    initials: "MC",
    email: "maya@northstar.studio",
    title: "Product Lead",
    role: "owner",
    color: "#ff7a66",
    availability: "available",
    online: true,
    floorId: "floor-studio",
    activity: "Product Studio",
    position: { x: 410, y: 650 },
  },
  {
    id: "user-leo",
    name: "Leo Martins",
    initials: "LM",
    email: "leo@northstar.studio",
    title: "Design Engineer",
    role: "admin",
    color: "#5b8def",
    availability: "available",
    online: true,
    floorId: "floor-studio",
    activity: "Commons",
    position: { x: 300, y: 310 },
  },
  {
    id: "user-amara",
    name: "Amara Okafor",
    initials: "AO",
    email: "amara@northstar.studio",
    title: "Engineering Lead",
    role: "admin",
    color: "#25b99a",
    availability: "busy",
    online: true,
    floorId: "floor-studio",
    activity: "Daily Room",
    position: { x: 735, y: 350 },
  },
  {
    id: "user-jonas",
    name: "Jonas Berg",
    initials: "JB",
    email: "jonas@northstar.studio",
    title: "Frontend Engineer",
    role: "member",
    color: "#f4b942",
    availability: "available",
    online: true,
    floorId: "floor-studio",
    activity: "Arcade",
    position: { x: 1230, y: 650 },
  },
  {
    id: "user-priya",
    name: "Priya Nair",
    initials: "PN",
    email: "priya@northstar.studio",
    title: "Product Designer",
    role: "member",
    color: "#b26fe8",
    availability: "dnd",
    online: true,
    floorId: "floor-studio",
    activity: "Focus Suite",
    position: { x: 1170, y: 250 },
  },
  {
    id: "user-noah",
    name: "Noah Williams",
    initials: "NW",
    email: "noah@northstar.studio",
    title: "Community",
    role: "member",
    color: "#e36d9e",
    availability: "available",
    online: true,
    floorId: "floor-rooftop",
    activity: "Garden",
    position: { x: 350, y: 370 },
  },
  {
    id: "user-elena",
    name: "Elena Rossi",
    initials: "ER",
    email: "elena@northstar.studio",
    title: "Backend Engineer",
    role: "member",
    color: "#ef8354",
    availability: "available",
    online: true,
    floorId: "floor-studio",
    activity: "Product Studio",
    position: { x: 650, y: 720 },
  },
  {
    id: "user-theo",
    name: "Theo Park",
    initials: "TP",
    email: "theo@northstar.studio",
    title: "QA Engineer",
    role: "member",
    color: "#3b82a0",
    availability: "available",
    online: true,
    floorId: "floor-studio",
    activity: "Open huddle",
    position: { x: 800, y: 760 },
  },
  {
    id: "user-aisha",
    name: "Aisha Khan",
    initials: "AK",
    email: "aisha@northstar.studio",
    title: "User Researcher",
    role: "member",
    color: "#ca6f9d",
    availability: "busy",
    online: true,
    floorId: "floor-rooftop",
    activity: "Cafe",
    position: { x: 1080, y: 620 },
  },
  {
    id: "user-sam",
    name: "Sam Rivera",
    initials: "SR",
    email: "sam@northstar.studio",
    title: "Operations",
    role: "member",
    color: "#7d8b99",
    availability: "away",
    online: false,
  },
  {
    id: "user-owen",
    name: "Owen Brooks",
    initials: "OB",
    email: "owen@northstar.studio",
    title: "Client Partner",
    role: "guest",
    color: "#8c7a6b",
    availability: "away",
    online: false,
  },
];

const studioAreas: Area[] = [
  {
    id: "area-commons",
    floorId: "floor-studio",
    name: "Commons",
    type: "lounge",
    x: 100,
    y: 100,
    width: 430,
    height: 310,
    color: "#f6c9a8",
    capacity: 8,
    locked: false,
    visibility: "public",
    doors: [],
  },
  {
    id: "area-daily",
    floorId: "floor-studio",
    name: "Daily Room",
    type: "meeting",
    x: 570,
    y: 100,
    width: 360,
    height: 310,
    color: "#c6d7f5",
    capacity: 8,
    locked: false,
    visibility: "public",
    doors: [{ id: "door-daily-south", side: "bottom", offset: 120, width: 90 }],
  },
  {
    id: "area-focus",
    floorId: "floor-studio",
    name: "Focus Suite",
    type: "private",
    x: 970,
    y: 100,
    width: 490,
    height: 310,
    color: "#d9cdf4",
    capacity: 5,
    locked: true,
    visibility: "public",
    memberIds: ["user-priya", "user-maya"],
    doors: [{ id: "door-focus-south", side: "bottom", offset: 250, width: 90 }],
  },
  {
    id: "area-product",
    floorId: "floor-studio",
    name: "Product Studio",
    type: "desk",
    x: 100,
    y: 460,
    width: 850,
    height: 390,
    color: "#cce6d8",
    capacity: 12,
    locked: false,
    visibility: "public",
    doors: [],
  },
  {
    id: "area-arcade",
    floorId: "floor-studio",
    name: "Arcade",
    type: "arcade",
    x: 990,
    y: 460,
    width: 470,
    height: 390,
    color: "#f2cfdf",
    capacity: 8,
    locked: false,
    visibility: "public",
    doors: [],
  },
];

const rooftopAreas: Area[] = [
  {
    id: "area-garden",
    floorId: "floor-rooftop",
    name: "Garden",
    type: "lounge",
    x: 90,
    y: 90,
    width: 560,
    height: 430,
    color: "#bcd9bc",
    capacity: 10,
    locked: false,
    visibility: "public",
    doors: [],
  },
  {
    id: "area-workshop",
    floorId: "floor-rooftop",
    name: "Workshop",
    type: "meeting",
    x: 700,
    y: 90,
    width: 490,
    height: 280,
    color: "#f0d5aa",
    capacity: 10,
    locked: false,
    visibility: "public",
    doors: [{ id: "door-workshop-west", side: "left", offset: 158, width: 82 }],
  },
  {
    id: "area-quiet",
    floorId: "floor-rooftop",
    name: "Quiet Corner",
    type: "private",
    x: 700,
    y: 420,
    width: 230,
    height: 250,
    color: "#cbd3ed",
    capacity: 4,
    locked: false,
    visibility: "members",
    memberIds: ["user-aisha", "user-noah"],
    doors: [{ id: "door-quiet-east", side: "right", offset: 86, width: 84 }],
  },
  {
    id: "area-cafe",
    floorId: "floor-rooftop",
    name: "Cafe",
    type: "kitchen",
    x: 960,
    y: 420,
    width: 230,
    height: 250,
    color: "#ead4c2",
    capacity: 6,
    locked: false,
    visibility: "public",
    doors: [],
  },
];

const studioObjects: WorldObject[] = [
  { id: "object-commons-table", floorId: "floor-studio", type: "table", x: 250, y: 220, width: 130, height: 70, color: "#ae795d", solid: true, interactive: false },
  { id: "object-commons-sofa-a", floorId: "floor-studio", type: "sofa", x: 135, y: 135, width: 120, height: 48, color: "#df8f72", solid: true, interactive: false },
  { id: "object-commons-sofa-b", floorId: "floor-studio", type: "sofa", x: 370, y: 320, width: 120, height: 48, color: "#df8f72", solid: true, interactive: false },
  { id: "object-daily-table", floorId: "floor-studio", type: "table", x: 655, y: 205, width: 190, height: 85, color: "#7893bd", solid: true, interactive: false },
  { id: "object-daily-board", floorId: "floor-studio", type: "whiteboard", x: 680, y: 125, width: 140, height: 24, color: "#f7f8f5", label: "Roadmap", solid: true, interactive: true },
  { id: "object-focus-desk-a", floorId: "floor-studio", type: "desk", x: 1030, y: 170, width: 110, height: 54, color: "#796ca6", solid: true, interactive: true },
  { id: "object-focus-desk-b", floorId: "floor-studio", type: "desk", x: 1240, y: 170, width: 110, height: 54, color: "#796ca6", solid: true, interactive: true },
  { id: "object-desk-maya", floorId: "floor-studio", type: "desk", x: 280, y: 590, width: 115, height: 58, color: "#6c9b83", label: "Maya", solid: true, interactive: true },
  { id: "object-desk-leo", floorId: "floor-studio", type: "desk", x: 520, y: 590, width: 115, height: 58, color: "#6c9b83", label: "Leo", solid: true, interactive: true },
  { id: "object-desk-amara", floorId: "floor-studio", type: "desk", x: 750, y: 590, width: 115, height: 58, color: "#6c9b83", label: "Amara", solid: true, interactive: true },
  { id: "object-product-board", floorId: "floor-studio", type: "whiteboard", x: 480, y: 495, width: 170, height: 24, color: "#f7f8f5", label: "Sprint", solid: true, interactive: true },
  { id: "object-stack", floorId: "floor-studio", type: "arcade", x: 1110, y: 580, width: 70, height: 100, color: "#34314a", label: "Stack", solid: true, interactive: true },
  { id: "object-arcade-b", floorId: "floor-studio", type: "arcade", x: 1300, y: 580, width: 70, height: 100, color: "#5a365f", label: "Dash", solid: true, interactive: true },
  { id: "object-portal-up", floorId: "floor-studio", type: "portal", x: 1450, y: 875, width: 54, height: 54, color: "#6c5ce7", label: "2", solid: false, interactive: true },
  { id: "object-plant-a", floorId: "floor-studio", type: "plant", x: 120, y: 760, width: 34, height: 34, color: "#4e8b68", solid: true, interactive: false },
  { id: "object-plant-b", floorId: "floor-studio", type: "plant", x: 900, y: 780, width: 34, height: 34, color: "#4e8b68", solid: true, interactive: false },
];

const rooftopObjects: WorldObject[] = [
  { id: "object-garden-table", floorId: "floor-rooftop", type: "table", x: 280, y: 260, width: 150, height: 80, color: "#8b6b4e", solid: true, interactive: false },
  { id: "object-garden-sofa", floorId: "floor-rooftop", type: "sofa", x: 150, y: 130, width: 150, height: 50, color: "#6e9d72", solid: true, interactive: false },
  { id: "object-workshop-table", floorId: "floor-rooftop", type: "table", x: 830, y: 180, width: 220, height: 85, color: "#aa8051", solid: true, interactive: false },
  { id: "object-rooftop-board", floorId: "floor-rooftop", type: "whiteboard", x: 865, y: 115, width: 160, height: 24, color: "#f7f8f5", label: "Ideas", solid: true, interactive: true },
  { id: "object-quiet-sofa", floorId: "floor-rooftop", type: "sofa", x: 735, y: 520, width: 140, height: 56, color: "#7c87b7", solid: true, interactive: false },
  { id: "object-cafe-table", floorId: "floor-rooftop", type: "table", x: 1030, y: 500, width: 130, height: 70, color: "#b98163", solid: true, interactive: false },
  { id: "object-cafe-plant", floorId: "floor-rooftop", type: "plant", x: 1130, y: 610, width: 36, height: 36, color: "#4e8b68", solid: true, interactive: false },
  { id: "object-portal-down", floorId: "floor-rooftop", type: "portal", x: 1130, y: 690, width: 54, height: 54, color: "#6c5ce7", label: "1", solid: false, interactive: true },
  { id: "object-plant-c", floorId: "floor-rooftop", type: "plant", x: 500, y: 400, width: 40, height: 40, color: "#39744d", solid: true, interactive: false },
];

const layouts: FloorLayout[] = [
  {
    floorId: "floor-studio",
    revision: 12,
    walls: [
      { id: "wall-studio-top", x: 60, y: 60, width: 1480, height: 20 },
      { id: "wall-studio-left", x: 60, y: 60, width: 20, height: 880 },
      { id: "wall-studio-right", x: 1520, y: 60, width: 20, height: 880 },
      { id: "wall-studio-bottom-a", x: 60, y: 920, width: 690, height: 20 },
      { id: "wall-studio-bottom-b", x: 820, y: 920, width: 720, height: 20 },
      { id: "wall-row-one-a", x: 80, y: 420, width: 160, height: 14 },
      { id: "wall-row-one-b", x: 330, y: 420, width: 360, height: 14 },
      { id: "wall-row-one-c", x: 780, y: 420, width: 440, height: 14 },
      { id: "wall-row-one-d", x: 1310, y: 420, width: 210, height: 14 },
      { id: "wall-col-a", x: 540, y: 80, width: 14, height: 260 },
      { id: "wall-col-b", x: 540, y: 380, width: 14, height: 40 },
      { id: "wall-col-c", x: 940, y: 80, width: 14, height: 150 },
      { id: "wall-col-d", x: 940, y: 320, width: 14, height: 100 },
      { id: "wall-col-e", x: 960, y: 430, width: 14, height: 170 },
      { id: "wall-col-f", x: 960, y: 690, width: 14, height: 230 },
    ],
    tiles: [],
    objects: studioObjects,
    areas: studioAreas,
  },
  {
    floorId: "floor-rooftop",
    revision: 8,
    walls: [
      { id: "wall-roof-top", x: 50, y: 50, width: 1180, height: 18 },
      { id: "wall-roof-left", x: 50, y: 50, width: 18, height: 700 },
      { id: "wall-roof-right", x: 1212, y: 50, width: 18, height: 700 },
      { id: "wall-roof-bottom-a", x: 50, y: 732, width: 560, height: 18 },
      { id: "wall-roof-bottom-b", x: 680, y: 732, width: 550, height: 18 },
      { id: "wall-roof-col-a", x: 670, y: 68, width: 16, height: 180 },
      { id: "wall-roof-col-b", x: 670, y: 330, width: 16, height: 330 },
      { id: "wall-roof-row", x: 686, y: 390, width: 526, height: 16 },
      { id: "wall-roof-lower-a", x: 940, y: 406, width: 16, height: 100 },
      { id: "wall-roof-lower-b", x: 940, y: 590, width: 16, height: 70 },
    ],
    tiles: [],
    objects: rooftopObjects,
    areas: rooftopAreas,
  },
];

const conversations: Conversation[] = [
  { id: "conversation-team", name: "Northstar", type: "team", unread: 3 },
  { id: "conversation-product", name: "Product Studio", type: "area", areaId: "area-product", unread: 0 },
  { id: "conversation-garden", name: "Garden", type: "area", areaId: "area-garden", unread: 1 },
  { id: "conversation-daily", name: "Daily Room", type: "meeting", meetingId: "meeting-product-crit", unread: 2 },
  { id: "conversation-open-huddle", name: "Open huddle", type: "meeting", meetingId: "meeting-open-huddle", unread: 0 },
  { id: "conversation-planning", name: "September planning", type: "meeting", meetingId: "meeting-planning", unread: 0 },
  { id: "conversation-leo", name: "Leo Martins", type: "direct", participantIds: ["user-maya", "user-leo"], unread: 0 },
  { id: "conversation-amara", name: "Amara Okafor", type: "direct", participantIds: ["user-maya", "user-amara"], unread: 1 },
  { id: "conversation-jonas", name: "Jonas Berg", type: "direct", participantIds: ["user-maya", "user-jonas"], unread: 0 },
  { id: "conversation-priya", name: "Priya Nair", type: "direct", participantIds: ["user-maya", "user-priya"], unread: 1 },
  { id: "conversation-noah", name: "Noah Williams", type: "direct", participantIds: ["user-maya", "user-noah"], unread: 0 },
  { id: "conversation-elena", name: "Elena Rossi", type: "direct", participantIds: ["user-maya", "user-elena"], unread: 1 },
  { id: "conversation-theo", name: "Theo Park", type: "direct", participantIds: ["user-maya", "user-theo"], unread: 0 },
  { id: "conversation-aisha", name: "Aisha Khan", type: "direct", participantIds: ["user-maya", "user-aisha"], unread: 1 },
  { id: "conversation-sam", name: "Sam Rivera", type: "direct", participantIds: ["user-maya", "user-sam"], unread: 1 },
  { id: "conversation-owen", name: "Owen Brooks", type: "direct", participantIds: ["user-maya", "user-owen"], unread: 0 },
];

function createMessages(now: Date): ChatMessage[] {
  return [
    { id: "message-team-1", conversationId: "conversation-team", userId: "user-amara", body: "API contract is ready for review.", createdAt: shiftedIso(now, -150), sequence: 1 },
    { id: "message-team-2", conversationId: "conversation-team", userId: "user-leo", body: "Nice. I left the latest flow on the board.", createdAt: shiftedIso(now, -145), sequence: 2 },
    { id: "message-team-3", conversationId: "conversation-team", userId: "user-elena", body: "The preview environment is stable again.", createdAt: shiftedIso(now, -138), sequence: 3 },
    { id: "message-team-4", conversationId: "conversation-team", userId: "user-jonas", body: "Stack score to beat: 4,820.", createdAt: shiftedIso(now, -126), sequence: 4 },
    { id: "message-team-5", conversationId: "conversation-team", userId: "user-maya", body: "Open huddle is live in the Product Studio.", createdAt: shiftedIso(now, -115), sequence: 5 },
    { id: "message-team-6", conversationId: "conversation-team", userId: "user-theo", body: "I will run the entry checks from there.", createdAt: shiftedIso(now, -112), sequence: 6 },
    { id: "message-product-1", conversationId: "conversation-product", userId: "user-maya", body: "Product crit starts in ten.", createdAt: shiftedIso(now, -92), sequence: 1 },
    { id: "message-product-2", conversationId: "conversation-product", userId: "user-priya", body: "I will bring the compact-mode pass.", createdAt: shiftedIso(now, -89), sequence: 2 },
    { id: "message-product-3", conversationId: "conversation-product", userId: "user-elena", body: "Loading states are ready for a look.", createdAt: shiftedIso(now, -84), sequence: 3 },
    { id: "message-product-4", conversationId: "conversation-product", userId: "user-maya", body: "Let us use the Daily Room.", createdAt: shiftedIso(now, -80), sequence: 4 },
    { id: "message-garden-1", conversationId: "conversation-garden", userId: "user-noah", body: "Coffee outside after planning?", createdAt: shiftedIso(now, -70), sequence: 1 },
    { id: "message-garden-2", conversationId: "conversation-garden", userId: "user-aisha", body: "Yes, I will bring the interview notes.", createdAt: shiftedIso(now, -67), sequence: 2 },
    { id: "message-garden-3", conversationId: "conversation-garden", userId: "user-noah", body: "Perfect.", createdAt: shiftedIso(now, -65), sequence: 3 },
    { id: "message-daily-1", conversationId: "conversation-daily", userId: "user-amara", body: "Join when you are ready.", createdAt: shiftedIso(now, -24), sequence: 1 },
    { id: "message-daily-2", conversationId: "conversation-daily", userId: "user-leo", body: "Reviewing the final flow now.", createdAt: shiftedIso(now, -19), sequence: 2 },
    { id: "message-daily-3", conversationId: "conversation-daily", userId: "user-priya", body: "I added the mobile frames.", createdAt: shiftedIso(now, -16), sequence: 3 },
    { id: "message-huddle-1", conversationId: "conversation-open-huddle", userId: "user-theo", body: "Entry checks are green.", createdAt: shiftedIso(now, -8), sequence: 1 },
    { id: "message-huddle-2", conversationId: "conversation-open-huddle", userId: "user-maya", body: "Great, joining in a minute.", createdAt: shiftedIso(now, -6), sequence: 2 },
    { id: "message-planning-1", conversationId: "conversation-planning", userId: "user-noah", body: "The workshop board has the draft agenda.", createdAt: shiftedIso(now, -55), sequence: 1 },
    { id: "message-planning-2", conversationId: "conversation-planning", userId: "user-aisha", body: "I added the research themes.", createdAt: shiftedIso(now, -51), sequence: 2 },
    { id: "message-leo-1", conversationId: "conversation-leo", userId: "user-leo", body: "Can you check the lounge spacing?", createdAt: shiftedIso(now, -132), sequence: 1 },
    { id: "message-leo-2", conversationId: "conversation-leo", userId: "user-maya", body: "On it.", createdAt: shiftedIso(now, -129), sequence: 2 },
    { id: "message-leo-3", conversationId: "conversation-leo", userId: "user-leo", body: "Thanks. I am by the commons table.", createdAt: shiftedIso(now, -124), sequence: 3 },
    { id: "message-amara-1", conversationId: "conversation-amara", userId: "user-amara", body: "Can we pair after the crit?", createdAt: shiftedIso(now, -41), sequence: 1 },
    { id: "message-amara-2", conversationId: "conversation-amara", userId: "user-maya", body: "Yes, meet me in the studio.", createdAt: shiftedIso(now, -38), sequence: 2 },
    { id: "message-jonas-1", conversationId: "conversation-jonas", userId: "user-maya", body: "How is the arcade input feeling?", createdAt: shiftedIso(now, -118), sequence: 1 },
    { id: "message-jonas-2", conversationId: "conversation-jonas", userId: "user-jonas", body: "Much tighter. Come try a round.", createdAt: shiftedIso(now, -114), sequence: 2 },
    { id: "message-priya-1", conversationId: "conversation-priya", userId: "user-priya", body: "I am in focus mode for the next half hour.", createdAt: shiftedIso(now, -36), sequence: 1 },
    { id: "message-priya-2", conversationId: "conversation-priya", userId: "user-maya", body: "Got it. I will knock if it is urgent.", createdAt: shiftedIso(now, -34), sequence: 2 },
    { id: "message-noah-1", conversationId: "conversation-noah", userId: "user-noah", body: "Rooftop planning still works for me.", createdAt: shiftedIso(now, -62), sequence: 1 },
    { id: "message-noah-2", conversationId: "conversation-noah", userId: "user-maya", body: "See you in the Workshop.", createdAt: shiftedIso(now, -59), sequence: 2 },
    { id: "message-elena-1", conversationId: "conversation-elena", userId: "user-elena", body: "Could you review the reconnect copy?", createdAt: shiftedIso(now, -31), sequence: 1 },
    { id: "message-elena-2", conversationId: "conversation-elena", userId: "user-maya", body: "Send it over.", createdAt: shiftedIso(now, -28), sequence: 2 },
    { id: "message-theo-1", conversationId: "conversation-theo", userId: "user-theo", body: "I am standing in the open meeting circle.", createdAt: shiftedIso(now, -10), sequence: 1 },
    { id: "message-aisha-1", conversationId: "conversation-aisha", userId: "user-aisha", body: "The first interview theme is ready.", createdAt: shiftedIso(now, -47), sequence: 1 },
    { id: "message-aisha-2", conversationId: "conversation-aisha", userId: "user-maya", body: "Add it to the planning thread.", createdAt: shiftedIso(now, -44), sequence: 2 },
    { id: "message-sam-1", conversationId: "conversation-sam", userId: "user-sam", body: "I will be back online this afternoon.", createdAt: shiftedIso(now, -75), sequence: 1 },
  ];
}

function createInvitations(now: Date): Invitation[] {
  return [
    { id: "invite-ana", teamId: team.id, email: "ana@example.com", role: "member", status: "pending", expiresAt: shiftedIso(now, 7 * 24 * 60) },
    { id: "invite-guest", teamId: team.id, email: "guest@example.com", role: "guest", status: "pending", expiresAt: shiftedIso(now, 3 * 24 * 60) },
    { id: "invite-revoked", teamId: team.id, email: "former@example.com", role: "member", status: "revoked", expiresAt: shiftedIso(now, 2 * 24 * 60) },
  ];
}

function createMeetings(now: Date): Meeting[] {
  return [
    { id: "meeting-product-crit", title: "Product crit", location: { type: "room", areaId: "area-daily" }, startsAt: shiftedIso(now, -12), durationMinutes: 30, status: "live", participantIds: ["user-amara", "user-leo"] },
    { id: "meeting-open-huddle", title: "Open huddle", location: { type: "public", floorId: "floor-studio", x: 800, y: 760, radius: 82 }, startsAt: shiftedIso(now, -4), durationMinutes: 30, status: "live", participantIds: ["user-theo"] },
    { id: "meeting-planning", title: "September planning", location: { type: "room", areaId: "area-workshop" }, startsAt: shiftedIso(now, 50), durationMinutes: 45, status: "scheduled", participantIds: ["user-maya", "user-noah", "user-aisha"] },
    { id: "meeting-retro", title: "Sprint retro", location: { type: "room", areaId: "area-workshop" }, startsAt: shiftedIso(now, -100), durationMinutes: 45, status: "ended", participantIds: ["user-maya", "user-leo", "user-priya"] },
  ];
}

const miniGames: MiniGameDefinition[] = [
  { id: "game-stack", name: "Stack", accent: "#ff7a66", objectId: "object-stack" },
];

function createScores(now: Date): GameScore[] {
  return [
    { id: "score-jonas", definitionId: "game-stack", userId: "user-jonas", score: 4820, lines: 21, playedAt: shiftedIso(now, -24 * 60) },
    { id: "score-priya", definitionId: "game-stack", userId: "user-priya", score: 3640, lines: 17, playedAt: shiftedIso(now, -2 * 24 * 60) },
    { id: "score-leo", definitionId: "game-stack", userId: "user-leo", score: 2910, lines: 14, playedAt: shiftedIso(now, -80) },
    { id: "score-elena", definitionId: "game-stack", userId: "user-elena", score: 2540, lines: 13, playedAt: shiftedIso(now, -3 * 24 * 60) },
    { id: "score-theo", definitionId: "game-stack", userId: "user-theo", score: 2100, lines: 11, playedAt: shiftedIso(now, -4 * 24 * 60) },
    { id: "score-noah", definitionId: "game-stack", userId: "user-noah", score: 1760, lines: 9, playedAt: shiftedIso(now, -5 * 24 * 60) },
  ];
}

function shiftedIso(now: Date, minutes: number): string {
  return new Date(now.getTime() + minutes * 60_000).toISOString();
}

export function createSeedData(currentUserId = "user-maya", now = new Date()): BootstrapData {
  return structuredClone({
    currentUserId,
    team,
    office,
    floors,
    members,
    layouts,
    conversations,
    messages: createMessages(now),
    invitations: createInvitations(now),
    meetings: createMeetings(now),
    miniGames,
    scores: createScores(now),
  });
}
