import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright-core";
import { createGovernanceRecheckFixture, clickWorld } from "./governance-recheck-fixture.js";
import { projectPreviewBounds } from "../apps/client/src/project-preview.js";

const output = fileURLToPath(new URL("../artifacts/governance-recheck/", import.meta.url));
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: "msedge", headless: true });
const fixture = await createGovernanceRecheckFixture(browser);
const page = await fixture.login("maya");
const checks: string[] = [];
const errors: string[] = [];
page.on("pageerror", (error) => errors.push(error.message));
try {
  await page.getByRole("button", { name: "Build", exact: true }).click();
  await page.getByRole("button", { name: "Shared", exact: true }).click();
  await page.getByRole("toolbar", { name: "Layout tools" }).waitFor();
  await clickWorld(page, 432, 208);
  await page.getByRole("region", { name: "Selected Floor plant", exact: true }).waitFor();
  await page.getByRole("button", { name: "Remove", exact: true }).click();
  await page.getByText(/Purchases 0 · Refund/).waitFor();
  const draft = fixture.events.findLast((event) => event.type === "project.preview");
  assert(draft?.type === "project.preview");
  assert.equal(draft.project.quote.refund, Math.floor(fixture.paidPrice / 3));
  assert(fixture.store.getLayout(fixture.floorId)!.objects.some((object) => object.id === "paid-plant"));
  await page.screenshot({ path: `${output}/refund-desktop.png` });
  for (const [name, viewport] of [["mobile", { width: 390, height: 844 }], ["small", { width: 320, height: 568 }], ["landscape", { width: 844, height: 390 }]] as const) {
    await page.setViewportSize(viewport);
    await page.screenshot({ path: `${output}/refund-${name}.png` });
    const refundBounds = await page.getByText(/Purchases 0 · Refund/).boundingBox();
    const discardBounds = await page.getByRole("button", { name: "Discard", exact: true }).boundingBox();
    assert(refundBounds && refundBounds.y >= 0 && refundBounds.y + refundBounds.height <= viewport.height, `${name}: refund must stay visible`);
    assert(discardBounds && discardBounds.y + discardBounds.height <= viewport.height, `${name}: draft actions must stay visible`);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${name}: horizontal overflow`);
  }
  await page.getByRole("button", { name: "Discard", exact: true }).click();
  assert.equal(fixture.store.getPublicEconomy().funds[0]!.balance, 100 - fixture.paidPrice);
  checks.push("Paid removal previews its recorded one-third refund; discarding leaves the asset and balances untouched");

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("button", { name: "Select", exact: true }).click();
  await clickWorld(page, 432, 208);
  await page.getByRole("button", { name: "Remove", exact: true }).click();
  await page.getByRole("textbox", { name: "Project name", exact: true }).fill("Remove shared plant");
  await page.getByRole("button", { name: "Propose project", exact: true }).click();
  await page.getByRole("dialog", { name: "Approvals", exact: true }).waitFor();
  const proposal = fixture.store.getPublicEconomy().proposals.at(-1)!;
  await page.getByRole("button", { name: "Close approvals", exact: true }).click();
  await page.getByRole("button", { name: "Build", exact: true }).click();
  await page.getByRole("button", { name: "Personal", exact: true }).click();
  await page.getByRole("button", { name: "Place", exact: true }).click();
  const editsBeforeBlockedPlacement = fixture.commands.filter((command) => command.type === "project.edit").length;
  await clickWorld(page, 320, 320);
  assert.equal(fixture.commands.filter((command) => command.type === "project.edit").length, editsBeforeBlockedPlacement);
  await clickWorld(page, 576, 416);
  checks.push("Placement over another player is blocked without changing the draft or balances");
  await page.getByText("1 in draft", { exact: false }).waitFor();
  const personalDraft = fixture.events.findLast((event) => event.type === "project.preview");
  assert(personalDraft?.type === "project.preview");
  await page.getByRole("textbox", { name: "Project name", exact: true }).fill("Personal workspace");
  await page.getByRole("navigation", { name: "Workspace", exact: true }).getByRole("button", { name: "Approvals", exact: true }).click();
  await page.getByRole("article", { name: proposal.title }).getByRole("button", { name: "View layout", exact: true }).click();
  await page.getByRole("button", { name: "Back to approvals", exact: true }).click();
  await page.getByRole("button", { name: "Close approvals", exact: true }).click();
  await page.getByRole("button", { name: "Build", exact: true }).click();
  assert(await page.getByText("Draft · not placed", { exact: true }).count(), "Reviewing someone else's proposal must preserve the working draft");
  assert.equal(await page.getByRole("textbox", { name: "Project name", exact: true }).inputValue(), "Personal workspace");
  checks.push("Reviewing a proposal preserves the user's existing draft and name");
  await page.getByRole("button", { name: "Shared", exact: true }).click();
  await page.getByRole("tab", { name: "Plants", exact: true }).click();
  await page.getByRole("button", { name: "Floor plant", exact: true }).click();
  await clickWorld(page, 576, 192);
  await page.getByText(`Purchases ${fixture.paidPrice} · Refund 0`, { exact: true }).waitFor();
  await page.getByRole("button", { name: "Wall", exact: true }).click();
  await clickWorld(page, 576, 608);
  await clickWorld(page, 640, 608);
  await page.getByText(`Purchases ${fixture.paidPrice + 24} · Refund 0`, { exact: true }).waitFor();
  const mixedDraft = fixture.events.findLast((event) => event.type === "project.preview");
  assert(mixedDraft?.type === "project.preview");
  assert.equal(mixedDraft.project.id, personalDraft.project.id);
  assert.equal(mixedDraft.project.quote.structural, true);
  assert.deepEqual(mixedDraft.project.quote.assetChanges.map(({ object }) => object.ownerUserId), ["user-maya", undefined]);
  assert.equal(await page.getByRole("button", { name: "Propose project", exact: true }).isEnabled(), false);
  const donation = mixedDraft.project.quote.cost - fixture.store.getPublicEconomy().funds[0]!.balance;
  await page.getByRole("navigation", { name: "Workspace", exact: true }).getByRole("button", { name: "Approvals", exact: true }).click();
  await page.getByRole("tab", { name: "Donate", exact: true }).click();
  await page.getByRole("spinbutton", { name: "Donation", exact: true }).fill(String(donation));
  await page.getByRole("button", { name: "Review donation", exact: true }).click();
  await page.getByRole("button", { name: "Edit amount", exact: true }).click();
  assert.equal(fixture.store.getPlayerEconomy("user-maya").coinBalance, 250 - fixture.paidPrice);
  await page.getByRole("button", { name: "Review donation", exact: true }).click();
  await page.getByRole("button", { name: "Donate coins", exact: true }).click();
  await page.getByText("Donation sent.", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Close approvals", exact: true }).click();
  await page.getByRole("button", { name: "Build", exact: true }).click();
  assert.equal(await page.getByRole("textbox", { name: "Project name", exact: true }).inputValue(), "Personal workspace");
  checks.push("One draft combines walls, public purchases and private inventory; insufficient funds prevent submission and donation cancellation preserves the wallet");
  await page.getByRole("button", { name: "Propose project", exact: true }).click();
  await page.getByRole("article", { name: "Personal workspace", exact: true }).waitFor();
  await page.getByRole("article", { name: proposal.title }).getByRole("button", { name: "Cancel proposal", exact: true }).click();
  assert.equal(fixture.store.publicEconomy.proposal(proposal.id).status, "cancelled");
  const personalProposal = fixture.store.getPublicEconomy().proposals.find((entry) => entry.title === "Personal workspace")!;
  assert.equal(fixture.store.getOwnedAsset("user-maya", fixture.owned.id).placement, undefined);
  const jonas = await fixture.login("jonas");
  jonas.on("pageerror", (error) => errors.push(error.message));
  await jonas.getByRole("navigation", { name: "Workspace", exact: true }).getByRole("button", { name: "Approvals", exact: true }).click();
  const card = jonas.getByRole("article", { name: "Personal workspace", exact: true });
  await card.getByText("Place · Personal · Maya Chen", { exact: true }).waitFor();
  await card.getByText("Place · Shared", { exact: true }).waitFor();
  await card.getByText("Construction changes", { exact: true }).waitFor();
  await jonas.screenshot({ path: `${output}/mixed-approval.png` });
  await card.getByRole("button", { name: "View layout", exact: true }).click();
  await jonas.getByRole("button", { name: "Back to approvals", exact: true }).waitFor();
  assert.equal(await jonas.getByRole("toolbar", { name: "Layout tools", exact: true }).count(), 0);
  const previewBounds = projectPreviewBounds(fixture.store.getLayout(fixture.floorId)!, mixedDraft.project)!;
  for (const [name, viewport] of [["desktop", { width: 1440, height: 1000 }], ["mobile", { width: 390, height: 844 }]] as const) {
    await jonas.setViewportSize(viewport);
    await jonas.waitForFunction((bounds) => {
      const layer = globalThis.findAvatar("You")!.parent!.parent!.parent!;
      const start = layer.toGlobal({ x: bounds.x, y: bounds.y });
      const end = layer.toGlobal({ x: bounds.x + bounds.width, y: bounds.y + bounds.height });
      const canvas = document.querySelector(".world-canvas canvas")!.getBoundingClientRect();
      return start.x >= 0 && start.y >= 0 && end.x <= canvas.width && end.y <= canvas.height;
    }, previewBounds);
    await jonas.screenshot({ path: `${output}/mixed-preview-${name}.png` });
  }
  checks.push("Proposal previews frame the changes on desktop and mobile without moving the voter");
  await jonas.getByRole("button", { name: "Close proposal preview", exact: true }).click();
  await jonas.setViewportSize({ width: 1440, height: 1000 });
  await card.getByRole("button", { name: "Approve", exact: true }).click();
  for (const userId of personalProposal.electorate) {
    const current = fixture.store.publicEconomy.proposal(personalProposal.id);
    if (current.status !== "open" || current.ballots.some((ballot) => ballot.userId === userId)) continue;
    const peer = fixture.runtime.connect(userId, fixture.floorId, () => undefined);
    fixture.runtime.handleCommand(peer, { type: "public_economy.vote", requestId: crypto.randomUUID(), proposalId: personalProposal.id, approve: true });
    fixture.runtime.disconnect(peer);
  }
  await page.getByRole("article", { name: "Personal workspace", exact: true }).getByRole("button", { name: "Apply proposal", exact: true }).click();
  await page.getByText("No votes waiting.", { exact: true }).waitFor();
  assert(fixture.store.getOwnedAsset("user-maya", fixture.owned.id).placement);
  assert.equal(fixture.store.getPublicEconomy().funds[0]!.balance, 0);
  assert(fixture.store.getLayout(fixture.floorId)!.objects.some((object) => object.id === "paid-plant"));
  checks.push("Voters see the wall, public item and personal owner; applying charges the public purchase once and retains private ownership");
  await page.getByRole("button", { name: "Close approvals", exact: true }).click();
  await page.getByRole("button", { name: "Build", exact: true }).click();
  await page.getByRole("button", { name: "Personal", exact: true }).click();
  await page.getByRole("tab", { name: "Placed", exact: true }).click();
  await page.getByRole("button", { name: /^Focus Floor plant/ }).click();
  await page.getByRole("button", { name: "Store", exact: true }).click();
  await page.getByText("No placed items yet.", { exact: true }).waitFor();
  assert.equal(fixture.store.getOwnedAsset("user-maya", fixture.owned.id).placement, undefined);
  await page.getByRole("tab", { name: "Inventory", exact: true }).click();
  await page.getByRole("button", { name: "Place", exact: true }).click();
  await clickWorld(page, 128, 128);
  await page.getByText("0 available · 1 placed", { exact: true }).waitFor();
  assert(fixture.store.getOwnedAsset("user-maya", fixture.owned.id).placement);
  assert.equal(fixture.store.getPublicEconomy().proposals.length, 2);
  assert.equal(fixture.store.getPlayerEconomy("user-maya").coinBalance, 250 - fixture.paidPrice - donation);
  checks.push("Owners recover their approved public placements without votes and can place them directly in their own areas");
  assert.deepEqual(errors, []);
} catch (error) {
  await writeFile(`${output}/edge-events.json`, JSON.stringify({ commands: fixture.commands, events: fixture.events.filter((event) => event.type === "command.error" || event.type === "project.preview") }, null, 2));
  await page.screenshot({ path: `${output}/edge-failure.png` });
  await writeFile(`${output}/edge-failure.txt`, await page.locator("body").innerText());
  throw error;
} finally {
  await writeFile(`${output}/edge-result.json`, JSON.stringify({ checks, errors }, null, 2));
  await fixture.close();
  await browser.close();
}
