export const FALLING_BLOCKS_WIDTH = 10;
export const FALLING_BLOCKS_HEIGHT = 20;
export const FALLING_BLOCKS_SPEED_STEP_MS = 30_000;
export const FALLING_BLOCKS_HARD_ROW_INTERVAL_MS = 30_000;
export const FALLING_BLOCKS_ATTACK_DELAY_MS = 3_000;
